# Generated by Django 4.2 on 2025-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='entry_type',
            field=models.CharField(choices=[('single', 'Single Visitor'), ('group', 'Group Entry')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='group_label',
            field=models.CharField(blank=True, help_text='Optional group/team name', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
