# Generated by Django 4.2 on 2026-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_visitor_entry_type_visitor_whatsapp_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='whatsapp_attempts',
            new_name='whatsapp_retry',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
