# Generated by Django 4.2 on 2026-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_rename_whatsapp_attempts_visitor_whatsapp_retry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='whatsapp_retry',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='whatsapp_sent',
        ),
        migrations.AddField(
            model_name='visitor',
            name='entry_type',
            field=models.CharField(choices=[('single', 'Single Visitor'), ('group', 'Group Entry')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
