# Generated by Django 4.2 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_remove_visitor_whatsapp_retry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='entry_type',
        ),
        migrations.AddField(
            model_name='visitor',
            name='category',
            field=models.CharField(choices=[('student', 'Student'), ('business', 'Business Owner'), ('investor', 'Investor'), ('vendor', 'Vendor'), ('job', 'Job Seeker')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='lead_score',
            field=models.CharField(choices=[('hot', 'Hot 🔥'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='whatsapp_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='whatsapp_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
